修改chatId字段为string由前端传来，修改删除chat的请求为Post
yacw-team/yacw-backend pull request #22
Opened 2023-05-22 14:00 UTC by FindCollector

#17 #16

2023-05-23 05:17 UTC, Kare-Udon requested changes
为什么删掉了所有的测试函数呢

2023-05-23 05:17 UTC, Kare-Udon requested changes
为什么删掉了所有的测试函数呢

2023-05-23 14:48 UTC, Kare-Udon approved these changes

2023-05-24 06:18 UTC, fzuxpc approved these changes
good writings

2023-05-24 06:31 UTC, merged